{
	"data": "ENC[AES256_GCM,data:I2TrL2aKgLuH4PhWMne23TV2PVmp5dOeQwmMEtaDj0Tv55ijh5q5hpolESmUjfI2TvVtl+Hth9d4CkLgm84CgEUVGYoQbGEq2LWAGLwymqoz6OO0ShLnja8zzpmvxLJjzW0j9zb9SxVN74NY6Hi+7uC4bNbyaA9IsHsokrxGcU9OwYmW905+57cYp0GQNGz8/EvLy0VDrR7o2PHWDDzBBUoMeJvNbHf63/1kEDVsaVpiY2k899yn1AEIPLt0usOrOBwGT97JcIIEOdg4oYnh/Vay1wVVwGJadOXQnCUR9I4wc/gNOkrAXDIPT0fXMSeiuuJxSJ98Y1gptN9nBg4SuboR8tHkJWgiYevUlQwAA9SSyWSkF2UcLu4b+ne3nk2+NUyD+cYBCz99EBmD8fJ7ajK7RyiBKGdxzBQmpGxyeMksKHShrwBndh2v5cIKWRSBLL9y1nkLrelvEI3B1CyOzC2Wz/fL8jdvOzEObL4tXQqrk64lZ5GbPtuoT1Yf6GkfbLlKecUhCSi8ao/cgHYVQG7y,iv:Yz6pX8DBYoYJ6lCqZwZlIdxUYYszEh1TicZBfwC2m+o=,tag:NWLkvT9UOcKCsABmfdBAvA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": null,
		"lastmodified": "2022-02-04T09:52:57Z",
		"mac": "ENC[AES256_GCM,data:qRX233fqyb8kLN5aT2jBLYy2j1sEJ16Xkyvoqvh3aIcV4/Z/38mAaDcwp/sMu711hSbVqLV2gBLSwog39rhT5ZRVPjWT7/+JRnOV6/yw6m7m2d93gjeJj5ZjJlXd+F/zE6SdqavtqElu6NRTij00vYUGhGXG+NhMqWFFjSsdfcQ=,iv:ypRYQMt2RmI+JHLfO3Sd0LUQ35czru3ILQhnJfAEO+w=,tag:G1A1jEZSz1mMChe9vvR9jA==,type:str]",
		"pgp": [
			{
				"created_at": "2022-02-04T09:52:56Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhQIMA+yPlFtVebfYARAAqnA6YyqaCN4NXVrS6+/v9GkjoRjXPXXMJFjlFRpgHGkl\nS1BK/rnlF/NTJJyvV1wsN5DYCHFBiN++iPUc0IK4EKCfebivaK2LhtKVUxqLF/H6\nCrFBNP/qRbJJxqCTFtAjc4CuHZwMOtwcp6caPB6fRsTZ+r1IeqLgCUeJaXfykocb\nsgWj3CpGdVG9d7j0Pv33zF8tqH3savB4pvjfUU0/UhGNRYSy301SoqiiVNeKX09R\ng0BhJc+bN/iW1Oljz33J9HGcopen4+WnI45Wr2sfrYoBy9GyqlEye8uMbd4XaVu7\nu5VrllO8HhkA9QEdn/fZ+LQAqInessFGLrHEzHSDDrBpM1wW4GkC8oV6f5EESNLD\np4uRHkaQMYmum94z+15bEdB/ph3Lxp/E3fthiKmUW/prK76RlYK3+eu0WZbtcyKY\nXpqDYcJQzYGkIkbEElF0WH6lUQ7y9AABDpTalsTaoP2R/Ny2M27ilZDc2/aBIvYf\n9DVaRhFxVg6Ll/PEyvBg6Qz+lFCyothudiJT9z/3Gl2VD9KuMnfD5mh4nCShvqmt\njzINv7vSR7xbjJowe4VWn4sPTh2JhHvFNjNptothG3IvmrcZ7WLy4wdLHCLzqF5s\nVcGCBUqgKy9xMAJG98qp2lhOkJTYvjoTo9NN3FBd0HPZob3ISrD7gaWy21zSOh3S\nUQFJSWzEWZQdA2zkuI4hQ0fHJlHuvUc2mJsQu9egV6npHkzp3IfSv/wmPzcI3mKc\n1UUvHKhzKeJxc1w78021DPITApRB7EPHgUiZ77tnx/+c4A==\n=ueYa\n-----END PGP MESSAGE-----\n",
				"fp": "1d1a32d148edf1e8a536f7a08a82a50a2df52ee4"
			}
		],
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.1"
	}
}