{
	"data": "ENC[AES256_GCM,data:DqixygtyUbJ8Ri6QU7mt95zGBHk/V1sh4AQlA0bunKeL/cFNHbS8avP38BtViiVFyGKjK+cOcl0NFAk8bq4VzCtwqnhVnPY2/FArE0bqFkgfBy1rkyGBiSJJDKYgohNv5pUQjNUaoEeKg784+1oyERpC187yn+aTSeVX3I/11g/Gs97AauQNqL+WqiWyJ7M/updYuQpdWkO/TuWtfC6PYC1aOIDtgch3eltEUzaCgzyTBYIvZrz+j4cr1wMb2W5sQwulhSmmDNB6Ao5XStPRyDd9WJOBc3Ga3oRKU8EvGjqFrwDAajWJIY8q0trEtSZiVE9xTcM9Ftpv+Gzgkg6/+/c092maNT35Nq6B01bFdWE7yGkORTcxt4s0tCBaMdjQ5+Q0BIwGWpKgu8OkqhjqQdgmD+GQic0sHmeXMPeC3KlSwfQoeaFHzG89mUuMsIGX/tHUAlAT0LuNJLxfJlLk7YvzAXFyZIoNRKepQeH3sQc=,iv:QKkHlIPj/WeRqRerH6FKOCOKNNoKlmoCx4DJoj1OAE0=,tag:bUexqoc0vpLkIgFkUxWLKg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": null,
		"lastmodified": "2021-12-18T08:31:18Z",
		"mac": "ENC[AES256_GCM,data:8QJD7/BVu3syysREYiB5ga2sDJpMjBWAup7K3dE7/ZrCQ5BctoeohSsM3koq95vpO4ELe6v8EPJ4y5A+xb5OOhL40RZMSvQ2W/L8FZWXZTkY6hQ4L6ENeldNV9xnyUVBeyRMc2B7F/nxqGP1w3aCF5N1lWn9l6mNVouvTkKPYco=,iv:6ICch2orFH8xCjR/vnp12F5kBpxavxh1c7HX+RiTFWw=,tag:VodlmsZ3StsWWxplGRqo+w==,type:str]",
		"pgp": [
			{
				"created_at": "2021-12-18T08:31:15Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhQIMA+yPlFtVebfYARAAwQp9qcQXGVni/iaq6EgrWObFuo0MPPAvxoc97ka3uqnn\nxtEn3hXBDlHFTaYNzNlMeIMG38Mab+Bw6PAVYfpEqP6Xi3rUMaVADjCgZufG13Md\nYMmupwxgwhLlt6ecWfdwNxXrsib8qx7VBHY/0j/EDqebAcOlhAoL0ttULcNwFtTF\nVCuIN3xtURBXjBRloOCkRGfvmSEdNEEOb9xs6lB4IOOc+Bs6ki9Knk8z8YHQjj4c\n88zA7GCwT6j4oT4FULHRnuxYE6xVtbgJpPWId/1lB7owZdeon0oWxUyo4vnBYNXF\n60LSzwlYV1BR3Bp5LbKThCN/FX+M860DKhD5oU+AkcKWXLo3gndfRR0vmVkwekl6\nAamAjFISBkP3mpZPY6I8+m8D7v+zq53kXr/KRUs20giBPnclEgB3LEQW2gOBrheS\nPVdHpwR46BsTkvnpycKuGBqq3NsTsaPNhm/dNy8kaHpAC3uuEtJ4lu9sHGzRqASh\nJUzHqPs1x1+YinK3h6DqBmBgBOdcEFKjkySs6aFODMda5yqB45CuHfxqUiIB/Iqs\nBeGoGjQ8supjDPY1lLyBsdeLC3/yt0J7RvdVO95EkKVGJSSDf0akjCFAduhJtQAo\n+U+IsR+zDvYiSYRB/T7C+YH+sP5Rih4EJ1nRIHWVxwFHWZcxeRxwfZvETJUkUz3S\nUQFUyspUnZw+axn4aTRxCUD4RmBui1oJWoaUnFYMx+fQhvBtHTg+QHQ6FOX+5SvT\nQcoQZSDAeuIE1kXOQ417bsRZkfuyFU6+AzIB124Y3jgd7g==\n=gY+D\n-----END PGP MESSAGE-----\n",
				"fp": "1d1a32d148edf1e8a536f7a08a82a50a2df52ee4"
			}
		],
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.1"
	}
}