{
	"data": "ENC[AES256_GCM,data:RDt5E19J4f55EBgtNUxMiy8cIZVWT9l/VTTiibGs0VJ1q7OF5Nx0OY38z2F38UakeH0eTeM5LZyx8ucSstYsvfKMQnz3VL/gPsSm05i0fh1EoPupWQ5KIK31ZYhvVW1NK/D+VicGILsmEWVJcQjL0X4xztzIJvtDnwsAqpXMfkUDB1SdlTZQGlS7uRTGXL9oSZDnTzJIU5FAJaIdODm4cu47g4lvcpTVn/sZKgsZgm46UlEtSARhE7JbgX+NgCkQzMKgm+gnkvIn75xbVwP+2hJZto/Qo753pZl4FJiObRrdkGngXPyYfaVgy12aANzX9/1h5FQtExnIDeWFqI3zW9T3Jb4tE++7NazuGsPVl3cZrWZ4+4o7AL7uv9IZy7EIpaIAAEDuDb9aaQLca2adO5YiVpSqsXthUukUKEB/aagLBGV8I5kkfptZOkc7uqFf92NAMdoHvSuv8/alQV8uEU17ToLr0kh6BZGcLrsQUkm9iacSxEKoXMA31DESL1RoCgrt6wjfZN+k7NGSID/CxqUl7YvKOCMlmqkvpqIL5NQVzNF/ci29907OsmJL,iv:ocTOS2GKZExmR7PApZBJNyBbckYzpJimv4IfrCi55EA=,tag:Rj4wONkAtHOXb4SUkFi9Gw==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": null,
		"lastmodified": "2022-05-09T12:49:47Z",
		"mac": "ENC[AES256_GCM,data:PJ1XZleD8L1fuc2yOZqkdhR5+ln+5hdW+qjOS6x5xGXLK+BM0BVaB+CPOjrnAg1FfpdpYxphWBYbioWx8XnBP6MYmI9DtW4ILTyd0gBzd3w+rvtpQ/2jU0dEJDskzzPjXb8bnQ6E3c0sI+CLr48JChYOBBZWs6AbPDevxkcoEOg=,iv:5hKr+JOd4wSAnGd19FD1H6ner1gjCxqo/rxAqe5YZvw=,tag:kIUwG+h0B52hAlt7nZJ05Q==,type:str]",
		"pgp": [
			{
				"created_at": "2022-05-09T12:49:46Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhQIMA+yPlFtVebfYAQ//SLsIWfZBfbGVcmo/C4Ld6H1BquUqSBtmdDHv8/GRmPpB\nVw06HVhERZcBz+8pqvOp7XiWPXdBxn9qylw5gThehaSI5Klc4jRYg57mM7XrQuJN\nQpajEIjZpQKYiMFpvBVu8+zG8BhEZnGxor77j/rAFrfKZgAe+jKVu9UD4L0M81pf\nBy0o81yQ3utkfTA5ADNshr4A5tIS6Ce5eIu14TksLJ9h3sFDmXsDuwpur/M3hCUh\nf7GVNjXFgpexQWkbjJ7HqeWPNhaafclPdtm3/cmXt3kwGfkXdeY4ra9LojrGX5ZP\nif/jSubL1Mw0z2NEKjpiZ4Y1PjELEK8u2Tpz7HnXrUeAhRP5l/1BQgXEeCU+DexA\nBAmPCof8D7KaI8Q7Cgf3RdeIqtNqbg/HCJ8yFXsICmvwOlOt4l0cJCJUG33ihu6P\n9zbqFz5ljmc6ZuBXeSDlkZ21BcJeWiQW00uhHAv5yCLMm2mTiJIus58FpYSMWpF9\nIdFogfFJiFjQlDpq7acmHUfr+odSvdqUgEvnTEaMYRp2FOMcuFUcQCiT8oJ3Dfdh\n2x26/GYkFpSuW8KDYi+uuSZcsboUTox3p+DIXyM9qSjSwh56E/kW+gnRQteEh5uU\nYDkP7YDfbu2bvf/1bngRih97V0vsYUwz/JfKSEiIxPf9nQ1YvHxT1szWztq3jv3S\nUQF117SUds7a+e0yHfqZJbEkWbZTmwf0L2lJfnZTvInTwGaG3D4ZOXxdz7w2WE9A\nluK0hvRQ9NQpf6A16pF37TazzvrfQlk2X5rA1B/Qlw+7Jw==\n=zJS3\n-----END PGP MESSAGE-----\n",
				"fp": "1d1a32d148edf1e8a536f7a08a82a50a2df52ee4"
			}
		],
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.1"
	}
}